runtime: java21
env: standard
instance_class: F2
service: portfolioservice
handlers:
  - url: /.*
    script: auto
  - url: .*
    script: auto
env_variables:
#  CLOUD_SQL_CONNECTION_NAME: 'true-oasis-439517-g0:us-central1:hello-traders'
#  DB_NAME: "hello_traders"
#  DB_PASS: "system"
#  DB_USER: "systemuser"
#  SPRING_PROFILES_ACTIVE: dev
readiness_check:
  check_interval_sec: 5
  timeout_sec: 4
  app_start_timeout_sec: 300
  path: /management/health/readiness
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic